src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 */
class Projet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Github;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Link;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ApiLink;



    public function __construct()
    {
        $this->blas = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->Github;
    }

    public function setGithub(?string $Github): self
    {
        $this->Github = $Github;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getApiLink(): ?string
    {
        return $this->ApiLink;
    }

    public function setApiLink(string $ApiLink): self
    {
        $this->ApiLink = $ApiLink;

        return $this;
    }

}

src/Controller/BackoController.php
<?php

namespace App\Controller;

use App\Entity\Cv;
use App\Entity\Presentation;
use App\Entity\Projet;
use App\Form\CvFormType;
use App\Form\ProjetFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BackoController extends AbstractController
{
    /**
     * @Route("/backo", name="backo")
     */
    public function index(): Response
    {
        $LinkLinkedin = "https://www.linkedin.com/in/walidmoussa/";
        $LinkGithub = "https://github.com/rootbu";

        //On récup tout les cv..
        $Doc = $this->getDoctrine()->getManager();
        $RepCV = $Doc->getRepository(Cv::class);
        $CV = $RepCV->findAll();

        $RepPresentation = $Doc->getRepository(Presentation::class);
        $Presentation = $RepPresentation->find(1);

        //On récup tout les portfolio..
        $RepXP = $Doc->getRepository(Projet::class);
        $Projets = $RepXP->findAll();


        return $this->render('backo/index.html.twig', [
            'CVList' => $CV,
            'Projets' => $Projets,
            'Mode' => 'Backo',
            'Presentation' => $Presentation
        ]);
    }

    /**
     * @Route("/backo/ajouter-une-experience", name="AddCVForm")
     */
    public function AddCVForm(): Response
    {
        $Cv = new Cv();
        $Form = $this->createForm(CvFormType::class, $Cv, [
            'method' => 'POST',
            'action' => $this->generateUrl('AddCV')
        ]);

        return $this->render('backo/AddCvForm.html.twig',[
            'Form' => $Form->createView(),
            'Mode' => 'Add'
        ]);
    }


    /**
     * @Route("/backo/modifier-une-experience/{id}", name="UpdateCVForm")
     */
    public function UpdateCVForm($id): Response
    {
        $Doc = $this->getDoctrine()->getManager();
        $RepCv = $Doc->getRepository(Cv::class);
        $Cv = $RepCv->find($id);

        $Form = $this->createForm(CvFormType::class, $Cv, [
            'method' => 'POST',
            'action' => $this->generateUrl('UpdateCV', ['id' => $id])
        ]);

        return $this->render('backo/AddCvForm.html.twig',[
            'Form' => $Form->createView(),
            'Mode' => 'Update',
            'CV' => $Cv
        ]);
    }

    /**
     * @Route("/backo/ajouter-un-projet", name="AddProjetForm")
     */
    public function AddProjetForm(): Response
    {
        $Projet = new Projet();
        $Form = $this->createForm(ProjetFormType::class, $Projet, [
            'method' => 'POST',
            'action' => $this->generateUrl('AddProjet')
        ]);

        return $this->render('portfolio_crud/index.html.twig', [
            'Form' => $Form->createView(),
            'Mode' => 'Add'
        ]);
    }

    /**
     * @Route("/backo/modifier-un-projet/{id}", name="UpdateProjetForm")
     */
    public function UpdateProjetForm(Request $Request, $id): Response
    {
        $Doc = $this->getDoctrine()->getManager();
        $RepProjet = $Doc->getRepository(Projet::class);
        $Projet = $RepProjet->find($id);

        $Form = $this->createForm(ProjetFormType::class, $Projet, [
            'method' => 'POST',
            'action' => $this->generateUrl('UpdateProjet', ['id' => $id])
        ]);

        return $this->render('portfolio_crud/index.html.twig', [
            'Form' => $Form->createView(),
            'Projet' => $Projet,
            'Mode' => 'Update'
        ]);
    }


}

templates/backo/AddCvForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une expérience..{% endblock %}


{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('CSS/Backo/Backo.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/FloatLabel.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/Backo/AddForm.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/NoticeMsg.css') }}"/>

{% endblock %}

{% block body %}


    <main class="BackoMain">
        {% embed 'Partials/Notice.html.twig' %}{% endembed %}
        {% embed 'Partials/Error.html.twig' %}{% endembed %}

        <section class="AddForm">
            <p class="Title">
                {% if Mode == 'Add' %}
                Ajouter
                {% elseif Mode == 'Update' %}
                Modifier
                {% endif %}
                une nouvelle expérience :
            </p>

            {{ form_start(Form) }}

            <div class="FormGroup" >
                {{ form_widget(Form.title) }}
                {{ form_label(Form.title) }}
            </div>
            <div class="FormGroup" >
                {{ form_widget(Form.company) }}
                {{ form_label(Form.company) }}
            </div>
            <div class="FormGroup FormGroupTextarea" >
                {{ form_widget(Form.description) }}
                {{ form_label(Form.description) }}
            </div>
            <div class="FormGroup" >
                {{ form_widget(Form.start_date) }}
                {{ form_label(Form.start_date) }}
            </div>
            <div class="FormGroup" >
                {{ form_widget(Form.end_date) }}
                {{ form_label(Form.end_date) }}
            </div>

            {% if Mode == 'Add' %}
              {{ form_widget(Form.submit, {'label':'Ajouter une expérience'}) }}
            {% elseif Mode == 'Update' %}
              {{ form_widget(Form.submit, {'label':'Modifier cette expérience'}) }}<br/>
               <a href="{{ path('DeleteXP', {'id' : CV.getId()} ) }}" class="Delete">Supprimer cette expérience ? </a>
            {% endif %}

            {{ form_end(Form) }}
        </section>
    </main>
{% endblock %}

templates/backo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Backo..{% endblock %}


{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('CSS/CurriculumMain.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/CVCard.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/Backo/Backo.css') }}"/>
    <link rel="stylesheet" href="{{ asset('CSS/Backo/Presentation.css') }}"/>


    <link rel="stylesheet" href="{{ asset('CSS/NoticeMsg.css') }}"/>

{% endblock %}

{% block body %}


    <main class="BackoMain">
        {% embed 'Partials/Notice.html.twig' %}{% endembed %}
        {% embed 'Partials/Error.html.twig' %}{% endembed %}

        {% embed 'Partials/Presentation.html.twig' %}{% endembed %}

        <section id="AncreCV" class="Cv">

            <h2>CV actuel</h2>

            <div class="LinkAddCV">
            <a href="{{ path('AddCVForm') }}" class="LinkAddCV">Ajouter une expérience</a>
            </div>

            <div class="CvList">
                {% embed 'Partials/CVCardList.html.twig' %}{% endembed %}
            </div>
        </section>

        <section id="AncrePortfolio" class="Portfolio">

            <h2 class="PortfolioTitle">Portfloio</h2>
            <div class="LinkAddXP">
                <a href="{{ path('AddProjetForm') }}" class="LinkAddCV">Ajouter un projet</a>
            </div>

            <div class="XPListContainer">

                <table class="XPList">
                    <tr>
                        <th class="Title">Titre</th>
                        <th class="Desc">Description</td>
                        <th class="Img">Image</td>
                        <th class="Cat">Categorie</th>
                        <th class="Github">Github</th>
                        <th class="Link">Link</th>
                        <th class="Action">Action</th>
                    </tr>

                    {% for Projet in Projets %}
                        <tr>
                            <td class="Title">{{ Projet.getTitle() }}</td>
                            <td class="Desc">{{ Projet.getDescription() }}</td>
                            <td class="Img">{{ Projet.getImage() }}</td>
                            <td class="Cat">{{ Projet.getCategory() }}</td>
                            <td class="Github">{{ Projet.getGithub() }}</td>
                            <td class="Link"><a href="{{ Projet.getLink() }}" class="LinkProjet">{{ Projet.getLink() }}</a></td>
                            <td>
                                <a href="{{ path('UpdateProjetForm', {'id' : Projet.getId()}) }}" class="UpdateXPButton">Modifier</a>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </section>
    </main>

{% endblock %}